### ISSUE TITLE
The maximum value for an int type

### ISSUE THREAD

**Issue by awissu** [go-asn1-ber/asn1-ber#6] opened 2015-12-18 19:13 UTC
Hi!
The following program crashes on x86 architecture:

[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:83: constant 9223372036854775807 overflows int
[   82s] ../go/src/gopkg.in/asn1-ber.v1/length_test.go:137: constant 9223372036854775807 overflows int

See: https://build.opensuse.org/build/home:awissu:branches:devel:languages:go/openSUSE_Tumbleweed/i586/golang-gopkgin-asn1-ber/_log

**Comment by liggitt** [comment] 2015-12-18 19:17
dupe of https://github.com/go-asn1-ber/asn1-ber/issues/5

**Closed** 2017-05-06 16:17 UTC

**Comment by liggitt** [comment] 2017-05-11 17:03
published in [v1.2](https://github.com/go-asn1-ber/asn1-ber/releases/tag/v1.2)
